### ISSUE TITLE
Fix Distortion effect

### ISSUE THREAD

**Issue by zhijazi** [pmeas/pmeas-backend#13]
Distortion currently applies a very loud noise that drowns out all audio. Find and fix the issue.

**Comment by joshwahwalters** [comment]
I'm going to begin debugging this issue, I'll keep discussion going as I figure more out.

**Comment by Druage** [comment]
How'd you solve this?

**Comment by zhijazi** [comment]
I propose that before closing an issue, in your commit put "Fixes #13" (or whatever issue it addresses to have a link to the change that fixes it).

See this issue: https://github.com/pmeas/pmeas-frontend/issues/13

**Comment by joshwahwalters** [comment]
The 'drive' Pyo parameter was being truncated. It was forced to be an 'Int' so I updated it to be 'float'. The other issue with it not sounding of high quality is not on our end of implementation. The quality of effect is going to correlate with the user's sound card. This will not be an issue if the user has an audio interface.

**Comment by Druage** [comment]
You tested it with an audio interface that removes the noise?

**Comment by joshwahwalters** [comment]
Basing this off of researching this issue. It is a very common problem for musicians playing through their machines. The fix for the user is to update to a higher quality sound card designed for audio engineering or use an audio interface.
