### ISSUE TITLE
Fix IP Discovery for bridge

### ISSUE THREAD

**Issue by mattfg** [pmeas/pmeas-backend#21]

**Comment by Druage** [comment]
I was reading about this online and it seems that modern ethernet cables do have this direct connection capability, but will vary depending upon the age of the processor being used.

I am using a 2016 motherboard and an Intel Skylake processor and I cannot get this ethernet device to show up. I even manually set the IP address and submask net.

**Comment by Druage** [comment]
This point may be moot with using bluetooth and a wifi connection.

**Comment by zhijazi** [comment]
:skull: You will be missed :skull:
