### ISSUE TITLE
Implement a Bluetooth connection

### ISSUE THREAD

**Issue by mattfg** [pmeas/pmeas-backend#25]

**Comment by Druage** [comment]
Good luck to whomever!

**Comment by Druage** [comment]
I think I should do it! There's not gonna be that much code on this one.

**Comment by zhijazi** [comment]
Matt was telling me yesterday he might wanna dig into it. We'll see at the meeting :upside_down_face:

**Comment by Druage** [comment]
Okey dokey

**Comment by mattfg** [comment]
Update: This sucks!

**Comment by Druage** [comment]
This will not be completed.
