### ISSUE TITLE
Service Discovery for connecting to Frontend

### ISSUE THREAD

**Issue by YounesN** [pmeas/pmeas-backend#31]
So for the client to be able to find the server there are two different approaches I found. 
You can use zero-configurations like Bonjour or Avahi:

https://en.wikipedia.org/wiki/Bonjour_(software)
https://en.wikipedia.org/wiki/Avahi_(software)
https://doc.qt.io/archives/qq/qq23-bonjour.html

Or in your case you can manually do it on your own:

- On your client side create a TCP socket and a UDP socket and on the server side create a TCP server and a UDP server.
- On the client, send out a broadcast message saying "who is out there, i am a client" (Using the UDP socket)
- Once the packet is received on the server (UDP server of course), send a direct UDP packet back to the UDP socket saying "i am here, pick me this is my tcp ip address and tcp port" (you can get the address and port from the received packet). Here you can populate a list with the IP addresses and ports so that user can choose who he wants to connect to.
- When your ready to connect, just take the tcp address and port sent in the packet and connect the TCP socket on the client to the TCP server.

More info: https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol

**Comment by zhijazi** [comment]
I'm on it bois

**Comment by mattfg** [comment]
UDP done, TCP WIP

**Comment by zhijazi** [comment]
Completed as of #42
