### ISSUE TITLE
Minimize Latency

### ISSUE THREAD

**Issue by zhijazi** [pmeas/pmeas-backend#47]
Change settings to minimize latency as much as possible - research possibility of lowering frames/period on Pi.

**Comment by Druage** [comment]
In the quest to reduce latency we have some new weapons at our disposal!

* https://guitarextended.wordpress.com/2012/09/11/setting-up-the-raspberry-pi-for-pd-1-allocate-more-ram-to-cpu/
* http://ajaxsoundstudio.com/pyodoc/perftips.html

**Comment by Druage** [comment]
We have solved this with using a JACK buffer size of 512, and changing out the guitar cable. The old cable caused crazy XRuns.
